'use strict';
/** UI translation strings (carried over & extended from the original site). */
module.exports = {
  en: {
    nav_shop: 'Shop', nav_cat: 'Categories', nav_srv: 'Cyber Services',
    nav_why: 'Why Us', nav_contact: 'Contact', nav_faq: 'FAQ',
    chat: 'Chat Now', order_btn: 'Order on WhatsApp', view_details: 'View details',
    hero_pill: 'Open & ready to serve you',
    hero_title: 'Your one-stop shop for phones, tech & cyber services.',
    hero_sub: 'Latest smartphones, quality accessories, cables, chargers and PC gear — plus fast, reliable cyber services. All in one trusted place.',
    hero_browse: 'Browse Products', hero_order: 'Order on WhatsApp',
    stat_products: 'Products available', stat_customers: 'Happy customers', stat_delivery: 'Wilayas delivered',
    cat_title: 'Everything tech, under one roof',
    cat_sub: "From the newest phones to the smallest cable — we've got what you need.",
    featured_title: 'Featured products', featured_sub: 'Hand-picked best sellers and top deals.',
    shop_title: 'Shop all products', shop_sub: 'Filter, search and sort to find exactly what you need.',
    search_ph: 'Search products…', sort_label: 'Sort by',
    sort_newest: 'Newest', sort_price_asc: 'Price: Low to High', sort_price_desc: 'Price: High to Low',
    sort_name: 'Name (A–Z)', sort_popular: 'Most popular',
    filter_all: 'All', no_results: 'No products match your search.',
    in_stock: 'In stock', out_of_stock: 'Out of stock', low_stock: 'Low stock — order soon',
    save_label: 'Save', add_wishlist: 'Add to wishlist', in_wishlist: 'In wishlist',
    add_compare: 'Compare', related_title: 'You might also like',
    recently_viewed: 'Recently viewed',
    srv_title: 'Need a service done? We handle it.',
    srv_sub: 'Fast, professional and affordable — walk in or message us.',
    srv_ask: 'Ask about this',
    why_title: 'Shop with confidence',
    trust_genuine: 'Genuine Products', trust_genuine_d: 'Quality you can trust, every time.',
    trust_fast: 'Fast Service', trust_fast_d: 'Quick replies & quick fixes.',
    trust_fair: 'Fair Prices', trust_fair_d: 'Honest pricing, great value.',
    trust_easy: 'Easy Ordering', trust_easy_d: 'Order in one tap via WhatsApp.',
    testimonials_title: 'What our customers say',
    faq_title: 'Frequently asked questions',
    delivery_title: 'Delivery', warranty_title: 'Warranty', returns_title: 'Returns',
    cta_title: "Can't find what you're looking for?",
    cta_sub: "Message us on WhatsApp — tell us what you need and we'll source it for you at the best price.",
    cta_btn: 'Ask Us Anything',
    contact_title: 'Visit us or message us', c_store: 'Our Store', c_phone: 'Call / WhatsApp',
    c_hours: 'Opening Hours', c_msg: 'Message Us',
    map: 'Tap to open in Google Maps & get directions.',
    foot_about: 'Your trusted shop for phones, tech accessories, cables, chargers, PC gear and cyber services.',
    foot_shop: 'Shop', foot_company: 'Company', foot_help: 'Help', rights: 'All rights reserved.',
    newsletter_title: 'Get deals & new arrivals', newsletter_ph: 'Your email', subscribe: 'Subscribe',
    login: 'Log in', register: 'Sign up', logout: 'Log out', my_account: 'My account',
    wishlist_title: 'My wishlist', compare_title: 'Compare products',
    badge_cod: 'Cash on Delivery', badge_warranty: 'Warranty Included',
    badge_delivery: '58 Wilayas Delivery', badge_original: '100% Original',
  },
  fr: {
    nav_shop: 'Boutique', nav_cat: 'Catégories', nav_srv: 'Services Cyber',
    nav_why: 'Pourquoi nous', nav_contact: 'Contact', nav_faq: 'FAQ',
    chat: 'Discuter', order_btn: 'Commander sur WhatsApp', view_details: 'Voir le détail',
    hero_pill: 'Ouvert & prêt à vous servir',
    hero_title: 'Votre boutique unique pour téléphones, tech & services cyber.',
    hero_sub: 'Derniers smartphones, accessoires de qualité, câbles, chargeurs et matériel PC — plus des services cyber rapides et fiables. Le tout au même endroit.',
    hero_browse: 'Voir les produits', hero_order: 'Commander sur WhatsApp',
    stat_products: 'Produits disponibles', stat_customers: 'Clients satisfaits', stat_delivery: 'Wilayas livrées',
    cat_title: 'Toute la tech, au même endroit',
    cat_sub: "Du dernier téléphone au plus petit câble — nous avons ce qu'il vous faut.",
    featured_title: 'Produits en vedette', featured_sub: 'Meilleures ventes et bonnes affaires sélectionnées.',
    shop_title: 'Tous les produits', shop_sub: 'Filtrez, cherchez et triez pour trouver ce qu’il vous faut.',
    search_ph: 'Rechercher des produits…', sort_label: 'Trier par',
    sort_newest: 'Nouveautés', sort_price_asc: 'Prix : croissant', sort_price_desc: 'Prix : décroissant',
    sort_name: 'Nom (A–Z)', sort_popular: 'Plus populaires',
    filter_all: 'Tout', no_results: 'Aucun produit ne correspond à votre recherche.',
    in_stock: 'En stock', out_of_stock: 'Rupture de stock', low_stock: 'Stock faible — commandez vite',
    save_label: 'Économisez', add_wishlist: 'Ajouter aux favoris', in_wishlist: 'Dans les favoris',
    add_compare: 'Comparer', related_title: 'Vous pourriez aussi aimer',
    recently_viewed: 'Vus récemment',
    srv_title: "Besoin d'un service ? On s'en occupe.",
    srv_sub: 'Rapide, professionnel et abordable — passez nous voir ou écrivez-nous.',
    srv_ask: 'En savoir plus',
    why_title: 'Achetez en toute confiance',
    trust_genuine: 'Produits authentiques', trust_genuine_d: 'Une qualité fiable, à chaque fois.',
    trust_fast: 'Service rapide', trust_fast_d: 'Réponses et réparations rapides.',
    trust_fair: 'Prix justes', trust_fair_d: 'Des prix honnêtes, un excellent rapport qualité-prix.',
    trust_easy: 'Commande facile', trust_easy_d: 'Commandez en un clic via WhatsApp.',
    testimonials_title: 'Ce que disent nos clients',
    faq_title: 'Questions fréquentes',
    delivery_title: 'Livraison', warranty_title: 'Garantie', returns_title: 'Retours',
    cta_title: 'Vous ne trouvez pas ce que vous cherchez ?',
    cta_sub: "Écrivez-nous sur WhatsApp — dites-nous ce qu'il vous faut et nous le trouverons au meilleur prix.",
    cta_btn: 'Posez-nous vos questions',
    contact_title: 'Venez nous voir ou écrivez-nous', c_store: 'Notre magasin', c_phone: 'Appel / WhatsApp',
    c_hours: "Horaires d'ouverture", c_msg: 'Écrivez-nous',
    map: "Cliquez pour ouvrir Google Maps & obtenir l'itinéraire.",
    foot_about: 'Votre boutique de confiance pour téléphones, accessoires, câbles, chargeurs, matériel PC et services cyber.',
    foot_shop: 'Boutique', foot_company: 'Société', foot_help: 'Aide', rights: 'Tous droits réservés.',
    newsletter_title: 'Offres & nouveautés', newsletter_ph: 'Votre email', subscribe: "S'abonner",
    login: 'Connexion', register: 'Inscription', logout: 'Déconnexion', my_account: 'Mon compte',
    wishlist_title: 'Mes favoris', compare_title: 'Comparer les produits',
    badge_cod: 'Paiement à la livraison', badge_warranty: 'Garantie incluse',
    badge_delivery: 'Livraison 58 wilayas', badge_original: '100% original',
  },
  ar: {
    nav_shop: 'المتجر', nav_cat: 'الفئات', nav_srv: 'خدمات الإنترنت',
    nav_why: 'لماذا نحن', nav_contact: 'اتصل بنا', nav_faq: 'الأسئلة',
    chat: 'تواصل الآن', order_btn: 'اطلب عبر واتساب', view_details: 'عرض التفاصيل',
    hero_pill: 'مفتوحون وجاهزون لخدمتك',
    hero_title: 'وجهتك الأولى للهواتف والتقنية وخدمات الإنترنت.',
    hero_sub: 'أحدث الهواتف الذكية، إكسسوارات عالية الجودة، كابلات، شواحن ومستلزمات الحاسوب — بالإضافة إلى خدمات إنترنت سريعة وموثوقة. كل ذلك في مكان واحد موثوق.',
    hero_browse: 'تصفّح المنتجات', hero_order: 'اطلب عبر واتساب',
    stat_products: 'منتجات متوفرة', stat_customers: 'عملاء سعداء', stat_delivery: 'ولايات نوصل إليها',
    cat_title: 'كل ما يخص التقنية في مكان واحد',
    cat_sub: 'من أحدث الهواتف إلى أصغر كابل — لدينا ما تحتاجه.',
    featured_title: 'منتجات مميزة', featured_sub: 'أفضل المبيعات وأقوى العروض المنتقاة.',
    shop_title: 'كل المنتجات', shop_sub: 'فلتر وابحث ورتّب لتجد ما تحتاجه بالضبط.',
    search_ph: 'ابحث عن المنتجات…', sort_label: 'ترتيب حسب',
    sort_newest: 'الأحدث', sort_price_asc: 'السعر: من الأقل', sort_price_desc: 'السعر: من الأعلى',
    sort_name: 'الاسم (أ–ي)', sort_popular: 'الأكثر رواجًا',
    filter_all: 'الكل', no_results: 'لا توجد منتجات تطابق بحثك.',
    in_stock: 'متوفر', out_of_stock: 'نفد المخزون', low_stock: 'كمية محدودة — سارع بالطلب',
    save_label: 'وفّر', add_wishlist: 'أضف للمفضلة', in_wishlist: 'في المفضلة',
    add_compare: 'قارن', related_title: 'قد يعجبك أيضًا',
    recently_viewed: 'شوهدت مؤخرًا',
    srv_title: 'تحتاج خدمة؟ نحن نتكفّل بها.',
    srv_sub: 'سريع، احترافي وبأسعار مناسبة — زرنا أو راسلنا.',
    srv_ask: 'استفسر عن هذا',
    why_title: 'تسوّق بثقة',
    trust_genuine: 'منتجات أصلية', trust_genuine_d: 'جودة تثق بها في كل مرة.',
    trust_fast: 'خدمة سريعة', trust_fast_d: 'ردود سريعة وإصلاح سريع.',
    trust_fair: 'أسعار عادلة', trust_fair_d: 'أسعار صادقة وقيمة ممتازة.',
    trust_easy: 'طلب سهل', trust_easy_d: 'اطلب بنقرة واحدة عبر واتساب.',
    testimonials_title: 'ماذا يقول عملاؤنا',
    faq_title: 'الأسئلة الشائعة',
    delivery_title: 'التوصيل', warranty_title: 'الضمان', returns_title: 'الإرجاع',
    cta_title: 'لم تجد ما تبحث عنه؟',
    cta_sub: 'راسلنا عبر واتساب — أخبرنا بما تحتاجه وسنوفّره لك بأفضل سعر.',
    cta_btn: 'اسألنا عن أي شيء',
    contact_title: 'زرنا أو راسلنا', c_store: 'متجرنا', c_phone: 'اتصال / واتساب',
    c_hours: 'ساعات العمل', c_msg: 'راسلنا',
    map: 'اضغط لفتح خرائط Google والحصول على الاتجاهات.',
    foot_about: 'متجرك الموثوق للهواتف والإكسسوارات والكابلات والشواحن ومستلزمات الحاسوب وخدمات الإنترنت.',
    foot_shop: 'المتجر', foot_company: 'الشركة', foot_help: 'المساعدة', rights: 'جميع الحقوق محفوظة.',
    newsletter_title: 'عروض ووصولات جديدة', newsletter_ph: 'بريدك الإلكتروني', subscribe: 'اشترك',
    login: 'تسجيل الدخول', register: 'إنشاء حساب', logout: 'خروج', my_account: 'حسابي',
    wishlist_title: 'مفضلتي', compare_title: 'مقارنة المنتجات',
    badge_cod: 'الدفع عند الاستلام', badge_warranty: 'ضمان مرفق',
    badge_delivery: 'توصيل 58 ولاية', badge_original: '100% أصلي',
  },
};
